.\" Manpage for perse.
.\" Contact ville.ranki@iki.fi to correct errors or typos.
.TH man 8 "24 Oct 2017" "1.0" "perse man page"
.SH NAME
perse \- udev permissions manager
.SH SYNOPSIS
perse
.SH DESCRIPTION
perse is a graphical application that can change udev device permissions.
.SH OPTIONS
perse does not take any options.
.SH FILES
/lib/udev/rules.d/50-perse.rules

This file is created and managed by perse to apply udev rules as required.
.SH SEE ALSO
udev(7), udevadm(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Ville Ranki (ville.ranki@iki.fi)

